[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 1.0
title = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "IosevkaTermSlab Nerd Font", style = "Regular" }
bold = { family = "IosevkaTermSlab Nerd Font", style = "Bold" }
italic = { family = "IosevkaTermSlab Nerd Font", style = "Italic" }
bold_italic = { family = "IosevkaTermSlab Nerd Font", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = -1 }

[cursor]
style = { shape = "Block", blinking = "On" }

[selection]
save_to_clipboard = true
