[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.95
title = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "IosevkaTermSlab Nerd Font", style = "Regular" }
bold = { family = "IosevkaTermSlab Nerd Font", style = "Bold" }
italic = { family = "IosevkaTermSlab Nerd Font", style = "Italic" }
bold_italic = { family = "IosevkaTermSlab Nerd Font", style = "Bold Italic" }
size = 10.0
offset = { x = 0, y = -1 }

[cursor]
style = { shape = "Block", blinking = "On" }

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001Bb"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001Bf"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"
